version: "2"

networks:
   default:
      external:
          name: NETWORK_NAME
services:
  ca.ORG_NAME.DOMAIN_NAME.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ORG_NAME.DOMAIN_NAME.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
#      - ../crypto-config/fabric-ca:/etc/hyperledger/fabric-ca-server
      - ../crypto-config/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.ORG_NAME.DOMAIN_NAME.com
