
version: '2'

services:

    zookeeper:
        image: hyperledger/fabric-zookeeper
        ports:
            - 2181
            - 2888
            - 3888

    kafka:
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        ports:
            - 9092

    orderer:
        image: hyperledger/fabric-orderer
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=NETWORK_NAME
            - ORDERER_HOME=/var/hyperledger/orderer
            - FABRIC_LOGGING_SPEC=WARNING
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
            - ORDERER_GENERAL_LOCALMSPID=ordererMSP
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=file
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/channels/CHANNEL_NAME/orderer.block
          #  - CONFIGTX_ORDERER_ORDERERTYPE=etcdraft
            - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
            - CONFIGTX_ORDERER_BATCHTIMEOUT=2s
            - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
            # TLS settings
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/tls/ca.crt]
            - ORDERER_TLS_CLIENTAUTHREQUIRED=false
            - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@DOMAIN_NAME.com/tls/ca.crt
            - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@DOMAIN_NAME.com/tls/client.crt
            - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@DOMAIN_NAME.com/tls/client.key
        volumes:
            - ../channels/:/var/hyperledger/channels
            - ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/users:/var/hyperledger/users
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        ports:
          - '7050'

    couchdb:
        image: hyperledger/fabric-couchdb

    peer:
        image: hyperledger/fabric-peer
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#            - CORE_PEER_NETWORKID=NETWORK_NAME
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=NETWORK_NAME
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_PEER_ENDORSER_ENABLED=true
            - FABRIC_LOGGING_SPEC=WARNING
            - CORE_NEXT=true
            - CORE_LOGGING_GOSSIP=ERROR
            - CORE_LOGGING_MSP=ERROR
#            - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0.ORG_NAME.DOMAIN_NAME.com:7050
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=${CORE_PEER_TLS_CLIENTAUTHREQUIRED}
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
        volumes:
            - /var/run/:/host/var/run/
            - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config/:/var/hyperledger/crypto
            - ../channels/:/var/hyperledger/channels
        command: peer node start
        ports:
            - '7051'
            - '7053'

