---
Organizations:

    - &ordererorg
        Name: ordererorg
        ID: ordererMSP
        MSPDir: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ordererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ordererMSP.admin')"

    - &ORG_NAME
        Name: ORG_NAMEMSP
        ID: ORG_NAMEMSP
        MSPDir: ../crypto-config/peerOrganizations/ORG_NAME.DOMAIN_NAME.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ORG_NAMEMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ORG_NAMEMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ORG_NAMEMSP.admin')"
        AnchorPeers:
            - Host: peer0.ORG_NAME.DOMAIN_NAME.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults

    OrdererType: etcdraft
    Addresses:
        - orderer0.ORG_NAME.DOMAIN_NAME.com:7050
        - orderer1.ORG_NAME.DOMAIN_NAME.com:7050
        - orderer2.ORG_NAME.DOMAIN_NAME.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
   # Kafka:
   #     Brokers:
   #         - kafka0.ORG_NAME.DOMAIN_NAME.com:9092
   #         - kafka1.ORG_NAME.DOMAIN_NAME.com:9092
   #         - kafka2.ORG_NAME.DOMAIN_NAME.com:9092
   #         - kafka3.ORG_NAME.DOMAIN_NAME.com:9092
    EtcdRaft:
        Consenters:
        - Host: orderer0.ORG_NAME.DOMAIN_NAME.com
          Port: 7050
          ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer0.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
          ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer0.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
        - Host: orderer1.ORG_NAME.DOMAIN_NAME.com
          Port: 7050
          ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer1.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
          ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer1.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
        - Host: orderer2.ORG_NAME.DOMAIN_NAME.com
          Port: 7050
          ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer2.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
          ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer2.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *ordererorg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *ORG_NAME
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ORG_NAME
            Capabilities:
                <<: *ApplicationCapabilities
    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            #OrdererType: etcdraft
            #EtcdRaft:
            #    Consenters:
            #    - Host: orderer0.ORG_NAME.DOMAIN_NAME.com
            #      Port: 7050
            #      ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer0.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #      ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer0.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #    - Host: orderer1.ORG_NAME.DOMAIN_NAME.com
            #      Port: 7050
            #      ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer1.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #      ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer1.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #    - Host: orderer2.ORG_NAME.DOMAIN_NAME.com
            #      Port: 7050
            #      ClientTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer2.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #      ServerTLSCert: ../crypto-config/ordererOrganizations/DOMAIN_NAME.com/orderers/orderer2.ORG_NAME.DOMAIN_NAME.com/tls/server.crt
            #Addresses:
            #    - orderer0.ORG_NAME.DOMAIN_NAME.com:7050
            #    - orderer1.ORG_NAME.DOMAIN_NAME.com:7050
            #    - orderer2.ORG_NAME.DOMAIN_NAME.com:7050
                

            Organizations:
            - *ordererorg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *ordererorg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *ORG_NAME
                
  
