# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org3
  # ---------------------------------------------------------------------------
  - Name: ORG_NAME
    Domain: ORG_NAME.DOMAIN_NAME.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
